# fly.toml file generated for oris on 2023-03-29T06:20:48+01:00

app = "oris"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "jnb"
processes = []

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443